export const SET_TO_ALL_USERS = 'SET_TO_ALL_USERS'
export const RETURN_USERS_FROM_STORAGE = 'RETURN_USERS_FROM_STORAGE'
export const GET_TODOS_BY_USER_ID = 'GET_TODOS_BY_USER_ID'

export const SET_TODO_FOR_USER = 'SET_TODO_FOR_USER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const REMOVE_TODO = 'REMOVE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const MARK_DONE_TODO = 'MARK_DONE_TODO'